### ISSUE TITLE
Dos estilos distintos de tablas 

### ISSUE THREAD

**Issue by danielesc** [themostretarded/ProyectoFime70#4]
![tabla1](https://user-images.githubusercontent.com/7520341/30999495-2177698e-a49b-11e7-9d80-a1413ea3e979.PNG)
![tabla2](https://user-images.githubusercontent.com/7520341/30999496-2469ee6e-a49b-11e7-91ad-2af627a119c5.PNG)

**Comment by themostretarded** [comment]
Se refiere al text?
